//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2005.04.01 at 11:41:32 EST
//

package mjs.core.database.fielddef.impl.runtime;



/**
 * Generated classes have to implement this interface for it to be
 * unmarshallable.
 *
 * @author   Kohsuke KAWAGUCHI
 */
public interface UnmarshallableObject
{
   /**
    * Creates an unmarshaller that will unmarshall this object.
    *
    * @param context  Description of Parameter
    * @return         Description of Return Value
    */
   UnmarshallingEventHandler createUnmarshaller(UnmarshallingContext context);
}
