//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2005.04.01 at 11:41:32 EST
//

package mjs.core.database.fielddef.impl.runtime;

import com.sun.xml.bind.JAXBObject;
import org.xml.sax.SAXException;


/**
 * For a generated class to be serializable, it has to implement this
 * interface.
 *
 * @author   Kohsuke Kawaguchi
 */
public interface XMLSerializable extends JAXBObject
{
   /**
    * Serializes child elements and texts into the specified target.
    *
    * @param target            Description of Parameter
    * @exception SAXException  Description of Exception
    */
   void serializeBody(XMLSerializer target) throws SAXException;

   /**
    * Serializes attributes into the specified target.
    *
    * @param target            Description of Parameter
    * @exception SAXException  Description of Exception
    */
   void serializeAttributes(XMLSerializer target) throws SAXException;

   /**
    * Declares all the namespace URIs this object is using at its
    * top-level scope into the specified target.
    *
    * @param target            Description of Parameter
    * @exception SAXException  Description of Exception
    */
   void serializeURIs(XMLSerializer target) throws SAXException;

}
