// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users.bindings;

import com.sun.xml.rpc.client.BasicService;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class UserService_SerializerRegistry implements SerializerConstants {
    public UserService_SerializerRegistry() {
    }
    
    public TypeMappingRegistry getRegistry() {
        
        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping12 = registry.getTypeMapping(SOAP12Constants.NS_SOAP_ENCODING);
        TypeMapping mapping = registry.getTypeMapping(SOAPConstants.NS_SOAP_ENCODING);
        TypeMapping mapping2 = registry.getTypeMapping("");
        {
            QName type = new QName("http://www.shoemake.com/types", "getUser2Response");
            CombinedSerializer serializer = new mjs.home.commands.users.UserWebService_getUser_ResponseStruct1__UserService__LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,mjs.home.commands.users.UserWebService_getUser_ResponseStruct1.class, type, serializer);
        }
        {
            QName type = new QName("http://www.shoemake.com/types", "deleteUser2");
            CombinedSerializer serializer = new mjs.home.commands.users.UserWebService_deleteUser2_RequestStruct__UserService__LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,mjs.home.commands.users.UserWebService_deleteUser2_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://www.shoemake.com/types", "addUser");
            CombinedSerializer serializer = new mjs.home.commands.users.UserWebService_addUser_RequestStruct__UserService__LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,mjs.home.commands.users.UserWebService_addUser_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://www.shoemake.com/types", "updateUser2");
            CombinedSerializer serializer = new mjs.home.commands.users.UserWebService_updateUser2_RequestStruct__UserService__LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,mjs.home.commands.users.UserWebService_updateUser2_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://www.shoemake.com/types", "deleteUser");
            CombinedSerializer serializer = new mjs.home.commands.users.UserWebService_deleteUser_RequestStruct__UserService__LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,mjs.home.commands.users.UserWebService_deleteUser_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://www.shoemake.com/types", "getUserListResponse");
            CombinedSerializer serializer = new mjs.home.commands.users.UserWebService_getUserList_ResponseStruct__UserService__LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,mjs.home.commands.users.UserWebService_getUserList_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://www.shoemake.com/types", "getUser2");
            CombinedSerializer serializer = new mjs.home.commands.users.UserWebService_getUser2_RequestStruct__UserService__LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,mjs.home.commands.users.UserWebService_getUser2_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://www.shoemake.com/types", "getUserResponse");
            CombinedSerializer serializer = new mjs.home.commands.users.UserWebService_getUser_ResponseStruct__UserService__LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,mjs.home.commands.users.UserWebService_getUser_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://www.shoemake.com/types", "User");
            CombinedSerializer serializer = new mjs.home.model.User__UserService__LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,mjs.home.model.User.class, type, serializer);
        }
        {
            QName type = new QName("http://www.shoemake.com/types", "updateUser");
            CombinedSerializer serializer = new mjs.home.commands.users.UserWebService_updateUser_RequestStruct__UserService__LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,mjs.home.commands.users.UserWebService_updateUser_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://www.shoemake.com/types", "getUser");
            CombinedSerializer serializer = new mjs.home.commands.users.UserWebService_getUser_RequestStruct__UserService__LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,mjs.home.commands.users.UserWebService_getUser_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://www.shoemake.com/types", "getUserList");
            CombinedSerializer serializer = new mjs.home.commands.users.UserWebService_getUserList_RequestStruct__UserService__LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,mjs.home.commands.users.UserWebService_getUserList_RequestStruct.class, type, serializer);
        }
        return registry;
    }
    
    private static void registerSerializer(TypeMapping mapping, Class javaType, QName xmlType,
        Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer)ser));
    }
    
}
