// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users;


public class UserWebService_updateUser_RequestStruct {
    protected int int_1;
    protected mjs.home.model.User User_2;
    
    public UserWebService_updateUser_RequestStruct() {
    }
    
    public UserWebService_updateUser_RequestStruct(int int_1, mjs.home.model.User User_2) {
        this.int_1 = int_1;
        this.User_2 = User_2;
    }
    
    public int getInt_1() {
        return int_1;
    }
    
    public void setInt_1(int int_1) {
        this.int_1 = int_1;
    }
    
    public mjs.home.model.User getUser_2() {
        return User_2;
    }
    
    public void setUser_2(mjs.home.model.User User_2) {
        this.User_2 = User_2;
    }
}
