// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users;


public class UserWebService_getUser_ResponseStruct1 {
    protected mjs.home.model.User result;
    
    public UserWebService_getUser_ResponseStruct1() {
    }
    
    public UserWebService_getUser_ResponseStruct1(mjs.home.model.User result) {
        this.result = result;
    }
    
    public mjs.home.model.User getResult() {
        return result;
    }
    
    public void setResult(mjs.home.model.User result) {
        this.result = result;
    }
}
