// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users;


public class UserWebService_getUserList_RequestStruct {
    
    public UserWebService_getUserList_RequestStruct() {
    }
}
