// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users;


public class UserWebService_updateUser2_RequestStruct {
    protected java.lang.String String_1;
    protected mjs.home.model.User User_2;
    
    public UserWebService_updateUser2_RequestStruct() {
    }
    
    public UserWebService_updateUser2_RequestStruct(java.lang.String String_1, mjs.home.model.User User_2) {
        this.String_1 = String_1;
        this.User_2 = User_2;
    }
    
    public java.lang.String getString_1() {
        return String_1;
    }
    
    public void setString_1(java.lang.String String_1) {
        this.String_1 = String_1;
    }
    
    public mjs.home.model.User getUser_2() {
        return User_2;
    }
    
    public void setUser_2(mjs.home.model.User User_2) {
        this.User_2 = User_2;
    }
}
