// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users;


public class UserWebService_getUser_RequestStruct {
    protected int int_1;
    
    public UserWebService_getUser_RequestStruct() {
    }
    
    public UserWebService_getUser_RequestStruct(int int_1) {
        this.int_1 = int_1;
    }
    
    public int getInt_1() {
        return int_1;
    }
    
    public void setInt_1(int int_1) {
        this.int_1 = int_1;
    }
}
