// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users;


public class UserWebService_getUser2_RequestStruct {
    protected java.lang.String String_1;
    
    public UserWebService_getUser2_RequestStruct() {
    }
    
    public UserWebService_getUser2_RequestStruct(java.lang.String String_1) {
        this.String_1 = String_1;
    }
    
    public java.lang.String getString_1() {
        return String_1;
    }
    
    public void setString_1(java.lang.String String_1) {
        this.String_1 = String_1;
    }
}
