// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users;


public class UserWebService_addUser_RequestStruct {
    protected mjs.home.model.User User_1;
    
    public UserWebService_addUser_RequestStruct() {
    }
    
    public UserWebService_addUser_RequestStruct(mjs.home.model.User User_1) {
        this.User_1 = User_1;
    }
    
    public mjs.home.model.User getUser_1() {
        return User_1;
    }
    
    public void setUser_1(mjs.home.model.User User_1) {
        this.User_1 = User_1;
    }
}
