/* Generated by Together */

package mjs.core.model;

/**
 * This is the business object interface implemented by BusinessObjectImpl.
 * BusinessObjectImpl will be the baseclass for custom component models
 * and other business classes where the ID, type, and name are relevent.
 * <p>
 * All component baseclasses should have a model that extends from
 * BusinessObjectImpl.  However, the business objects will be referenced
 * by this interface for flexibility rather than referencing the baseclass
 * itself.
 */
public interface BusinessObject
{
   /**
    * The integer object ID.  This can be either specified in the constructor, set
    * using the set method, or the baseclass will auto generate a number that is unique for the class.
    */
   long getObjectID();

   /**
    * The integer object ID.  This can be either specified in the constructor, set
    * using the set method, or the baseclass will auto generate a number that is unique for the class.
    */
   void setObjectID(long value);

   /**
    * A user defined object type.  This can be used in conjunction with integer
    * constants defined by the developer.  It is not used internally for anything and is very flexible.
    */
   int getObjectType();

   /**
    * A user defined object type.  This can be used in conjunction with integer
    * constants defined by the developer.  It is not used internally for anything and is very flexible.
    */
   void setObjectType(int value);

   /**
    * The name associated with the object if applicable.
    */
   String getDisplayText();

   /**
    * The name associated with the object if applicable.
    */
   void setDisplayText(String displayText);
}


