/* Generated by Together */

package mjs.core.model;

// Java imports
import java.lang.Exception;

/**
 * This is the base business object class for custom component models
 * and other business classes where the ID, type, and name are relevent.
 * <p>
 * All component baseclasses should have a model that extends from
 * this class.
 */
public abstract class BusinessObjectImpl implements BusinessObject
{
   /**
    * Constructor.
    * @param   objectId   The unique, numeric ID used to distinguish the component from other components.
    */
   public BusinessObjectImpl(long objectId, String displayText)
   {
      try
      {
         setObjectID(objectId);
         setDisplayText(displayText);
      }
      catch (Exception ex)
      {
         ex.printStackTrace();
      }
   }

   /**
    * The integer object ID.  This can be either specified in the constructor, set
    * using the set method, or the baseclass will auto generate a number that is unique for the class.
    */
   public long getObjectID()
   {
      return objectID;
   }

   /**
    * The integer object ID.  This can be either specified in the constructor, set
    * using the set method, or the baseclass will auto generate a number that is unique for the class.
    */
   public void setObjectID(long value)
   {
      objectID = value;
   }

   /**
    * A user defined object type.  This can be used in conjunction with integer
    * constants defined by the developer.  It is not used internally for anything and is very flexible.
    */
   public int getObjectType()
   {
      return objectType;
   }

   /**
    * A user defined object type.  This can be used in conjunction with integer
    * constants defined by the developer.  It is not used internally for anything and is very flexible.
    */
   public void setObjectType(int value)
   {
      objectType = value;
   }

   /**
    * The name associated with the object if applicable.
    */
   public String getDisplayText()
   {
      return displayText;
   }

   /**
    * The name associated with the object if applicable.
    */
   public void setDisplayText(String displayText)
   {
      this.displayText = displayText;
   }

   /**
    * An integer object ID.  This can be either specified in the constructor, set
    * using the set method, or the baseclass will auto generate a number that is unique for the class.
    */
   private long objectID = 0;

   /**
    * A user defined object type.  This can be used in conjunction with integer
    * constants defined by the developer.  It is not used internally for anything and is very flexible.
    */
   private int objectType = 0;

   /**
    * The name associated with the object if applicable.
    */
   private String displayText = "";
}


