//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2005.04.01 at 11:41:32 EST
//


package mjs.core.database.fielddef;



/**
 * Java content class for FieldDefinition complex type. <p>
 *
 * The following schema fragment specifies the expected content
 * contained within this java content object. (defined at
 * file:/C:/work/ebar/common/jaxb_gen/TestMapping.xsd line 15) <p>
 *
 * <pre>
 * &lt;complexType name="FieldDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="ispercent" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="maxlen" type="{http://www.w3.org/2001/XMLSchema}integer" default="4000" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
public interface FieldDefinition
{

   /**
    * Gets the value of the type property.
    *
    * @return   possible object is {@link java.lang.String}
    */
   java.lang.String getType();

   /**
    * Sets the value of the type property.
    *
    * @param value  allowed object is {@link java.lang.String}
    */
   void setType(java.lang.String value);

   /**
    * Gets the value of the sequence property.
    *
    * @return   possible object is {@link java.lang.String}
    */
   java.lang.String getSequence();

   /**
    * Sets the value of the sequence property.
    *
    * @param value  allowed object is {@link java.lang.String}
    */
   void setSequence(java.lang.String value);

   /**
    * Gets the value of the name property.
    *
    * @return   possible object is {@link java.lang.String}
    */
   java.lang.String getName();

   /**
    * Sets the value of the name property.
    *
    * @param value  allowed object is {@link java.lang.String}
    */
   void setName(java.lang.String value);

   /**
    * Gets the value of the maxlen property.
    *
    * @return   possible object is {@link java.math.BigInteger}
    */
   java.math.BigInteger getMaxlen();

   /**
    * Sets the value of the maxlen property.
    *
    * @param value  allowed object is {@link java.math.BigInteger}
    */
   void setMaxlen(java.math.BigInteger value);

   /**
    * Gets the value of the ispercent property.
    *
    * @return   The value of the Ispercent property.
    */
   boolean isIspercent();

   /**
    * Sets the value of the ispercent property.
    *
    * @param value  The new Ispercent value.
    */
   void setIspercent(boolean value);

   /**
    * Gets the value of the format property.
    *
    * @return   possible object is {@link java.lang.String}
    */
   java.lang.String getFormat();

   /**
    * Sets the value of the format property.
    *
    * @param value  allowed object is {@link java.lang.String}
    */
   void setFormat(java.lang.String value);

}
