//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2005.04.01 at 11:41:32 EST
//


package mjs.core.database.fielddef;



/**
 * Java content class for FieldDefinitionList complex type. <p>
 *
 * The following schema fragment specifies the expected content
 * contained within this java content object. (defined at
 * file:/C:/work/ebar/common/jaxb_gen/TestMapping.xsd line 9) <p>
 *
 * <pre>
 * &lt;complexType name="FieldDefinitionList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="field" type="{http://www.accenture.com/core/model/fielddef}FieldDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
public interface FieldDefinitionList
{

   /**
    * Gets the value of the Field property. <p>
    *
    * This accessor method returns a reference to the live list, not a
    * snapshot. Therefore any modification you make to the returned
    * list will be present inside the JAXB object. This is why there
    * is not a <CODE>set</CODE> method for the Field property. <p>
    *
    * For example, to add a new item, do as follows: <pre>
    *    getField().add(newItem);
    * </pre> <p>
    *
    * Objects of the following type(s) are allowed in the list {@link
    * com.accenture.core.model.fielddef.FieldDefinition}
    *
    * @return   The value of the Field property.
    */
   java.util.List getField();

}
