//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.4-b18-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2005.04.01 at 11:41:32 EST
//


package mjs.core.database.fielddef;



/**
 * Java content class for field element declaration. <p>
 *
 * The following schema fragment specifies the expected content
 * contained within this java content object. (defined at
 * file:/C:/work/ebar/common/jaxb_gen/TestMapping.xsd line 7) <p>
 *
 * <pre>
 * &lt;element name="field" type="{http://www.accenture.com/core/model/fielddef}FieldDefinition"/>
 * </pre>
 */
public interface Field
       extends javax.xml.bind.Element, mjs.core.database.fielddef.FieldDefinition
{

}
