// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users.client;


public class AddUser {
    protected mjs.home.commands.users.client.User user_1;
    
    public AddUser() {
    }
    
    public AddUser(mjs.home.commands.users.client.User user_1) {
        this.user_1 = user_1;
    }
    
    public mjs.home.commands.users.client.User getUser_1() {
        return user_1;
    }
    
    public void setUser_1(mjs.home.commands.users.client.User user_1) {
        this.user_1 = user_1;
    }
}
