// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users.client;


public class GetUserResponse {
    protected mjs.home.commands.users.client.User result;
    
    public GetUserResponse() {
    }
    
    public GetUserResponse(mjs.home.commands.users.client.User result) {
        this.result = result;
    }
    
    public mjs.home.commands.users.client.User getResult() {
        return result;
    }
    
    public void setResult(mjs.home.commands.users.client.User result) {
        this.result = result;
    }
}
