// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users.client;


public class GetUser2 {
    protected java.lang.String string_1;
    
    public GetUser2() {
    }
    
    public GetUser2(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public java.lang.String getString_1() {
        return string_1;
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
}
