// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users.client;


public class GetUser {
    protected int int_1;
    
    public GetUser() {
    }
    
    public GetUser(int int_1) {
        this.int_1 = int_1;
    }
    
    public int getInt_1() {
        return int_1;
    }
    
    public void setInt_1(int int_1) {
        this.int_1 = int_1;
    }
}
