// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users.client;


public class UpdateUser {
    protected int int_1;
    protected mjs.home.commands.users.client.User user_2;
    
    public UpdateUser() {
    }
    
    public UpdateUser(int int_1, mjs.home.commands.users.client.User user_2) {
        this.int_1 = int_1;
        this.user_2 = user_2;
    }
    
    public int getInt_1() {
        return int_1;
    }
    
    public void setInt_1(int int_1) {
        this.int_1 = int_1;
    }
    
    public mjs.home.commands.users.client.User getUser_2() {
        return user_2;
    }
    
    public void setUser_2(mjs.home.commands.users.client.User user_2) {
        this.user_2 = user_2;
    }
}
