// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users.client;


public class UpdateUser2 {
    protected java.lang.String string_1;
    protected mjs.home.commands.users.client.User user_2;
    
    public UpdateUser2() {
    }
    
    public UpdateUser2(java.lang.String string_1, mjs.home.commands.users.client.User user_2) {
        this.string_1 = string_1;
        this.user_2 = user_2;
    }
    
    public java.lang.String getString_1() {
        return string_1;
    }
    
    public void setString_1(java.lang.String string_1) {
        this.string_1 = string_1;
    }
    
    public mjs.home.commands.users.client.User getUser_2() {
        return user_2;
    }
    
    public void setUser_2(mjs.home.commands.users.client.User user_2) {
        this.user_2 = user_2;
    }
}
