// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users.client;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class UserService_Impl extends com.sun.xml.rpc.client.BasicService implements UserService {
    private static final QName serviceName = new QName("http://www.shoemake.com/wsdl/UserService", "UserService");
    private static final QName ns1_UserWebServicePort_QNAME = new QName("http://www.shoemake.com/wsdl/UserService", "UserWebServicePort");
    private static final Class userWebService_PortClass = mjs.home.commands.users.client.UserWebService.class;
    
    public UserService_Impl() {
        super(serviceName, new QName[] {
                        ns1_UserWebServicePort_QNAME
                    },
            new mjs.home.commands.users.client.UserService_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(QName portName, Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_UserWebServicePort_QNAME) &&
                serviceDefInterface.equals(userWebService_PortClass)) {
                return getUserWebServicePort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(userWebService_PortClass)) {
                return getUserWebServicePort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public mjs.home.commands.users.client.UserWebService getUserWebServicePort() {
        String[] roles = new String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_UserWebServicePort_QNAME));
        handlerChain.setRoles(roles);
        mjs.home.commands.users.client.UserWebService_Stub stub = new mjs.home.commands.users.client.UserWebService_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
