// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users.client;

public interface UserWebService extends java.rmi.Remote {
    public void addUser(mjs.home.commands.users.client.AddUser parameters) throws 
         java.rmi.RemoteException;
    public void deleteUser(mjs.home.commands.users.client.DeleteUser parameters) throws 
         java.rmi.RemoteException;
    public void deleteUser2(mjs.home.commands.users.client.DeleteUser2 parameters) throws 
         java.rmi.RemoteException;
    public mjs.home.commands.users.client.GetUserResponse getUser(mjs.home.commands.users.client.GetUser parameters) throws 
         java.rmi.RemoteException;
    public mjs.home.commands.users.client.GetUser2Response getUser2(mjs.home.commands.users.client.GetUser2 parameters) throws 
         java.rmi.RemoteException;
    public mjs.home.commands.users.client.GetUserListResponse getUserList(mjs.home.commands.users.client.GetUserList parameters) throws 
         java.rmi.RemoteException;
    public void updateUser(mjs.home.commands.users.client.UpdateUser parameters) throws 
         java.rmi.RemoteException;
    public void updateUser2(mjs.home.commands.users.client.UpdateUser2 parameters) throws 
         java.rmi.RemoteException;
}
