// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1, build R59)

package mjs.home.commands.users.client;

import javax.xml.rpc.*;

public interface UserService extends javax.xml.rpc.Service {
    public mjs.home.commands.users.client.UserWebService getUserWebServicePort();
}
